### ISSUE TITLE
regarding the text file

### ISSUE THREAD

**Issue by praneethgillabathini** [Small-Samori/Machine-Learning-Models-Predict-Inhibitor-Dengue-Virus-2#1]
i didn't found the text file

**Comment by Small-Samori** [comment]
The text file that contains the SMILES notation used to be accessed through the Download Services link in the Download tab. I think the website has undergone maintenance and cannot be accessed there. I have attach the text file and data table to this comment. I hope this helps.
[all_datatable.csv](https://github.com/Small-Samori/Machine-Learning-Models-Predict-Inhibitor-Dengue-Virus-2/files/8014133/all_datatable.csv)
[smiles_dataset_txt.txt](https://github.com/Small-Samori/Machine-Learning-Models-Predict-Inhibitor-Dengue-Virus-2/files/8014135/smiles_dataset_txt.txt)

**Comment by praneethgillabathini** [comment]
Thank You
